/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import funciones.ValidarDatos;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import vergeflix.Capitulo;
import vergeflix.Temporada;

/**
 *
 * @author Heriberto Amezcua
 * @version 1.0
 * @since JDK 19
 */
public class JDAñadirCapitulo extends javax.swing.JDialog {

    private Temporada temporada;
    private boolean haAñadido;

    /**
     * Creates new form JDAñadirCapitulo
     */
    public JDAñadirCapitulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDAñadirCapitulo(java.awt.Frame parent, boolean modal, Temporada temporada) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("play-icon.png");
        setIconImage(icon.getImage());
        setTitle("VERGEFLIX");
        this.temporada = temporada;
        this.haAñadido = false;
    }

    public boolean getHaAñadido() {
        return this.haAñadido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelEmision = new javax.swing.JLabel();
        labelPosicion = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        textNombre = new javax.swing.JTextField();
        textFecha = new javax.swing.JTextField();
        textPosicion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Introducir Nuevo Capítulo");
        labelTitulo.setToolTipText("");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre.setText("Título:");

        labelEmision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmision.setText("Fecha de Emisión:");

        labelPosicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPosicion.setText("Posición:");

        btnAñadir.setText("AÑADIR");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(labelPosicion)
                                        .addGap(18, 18, 18)
                                        .addComponent(textPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(labelEmision))
                                .addGap(18, 18, 18)
                                .addComponent(textFecha))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(labelTitulo)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitulo)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmision)
                    .addComponent(textFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosicion)
                    .addComponent(textPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        if (!(textNombre.getText().isBlank() || textFecha.getText().isBlank() || textPosicion.getText().isBlank())) {
            boolean sePuedeAñadir = true;
            if (!ValidarDatos.validarTitulo(labelNombre.getText())) {
                sePuedeAñadir = false;
            }
            if (!ValidarDatos.validarFecha(textFecha.getText())) {
                sePuedeAñadir = false;
            }
            String fechaStr = textFecha.getText();
            int dia = Integer.parseInt(fechaStr.split("-")[0]);
            int mes = Integer.parseInt(fechaStr.split("-")[1]);
            int año = Integer.parseInt(fechaStr.split("-")[2]);
            if (!ValidarDatos.validarEmision(this.temporada.getFechaEstreno(), LocalDate.of(año, mes, dia))) {
                sePuedeAñadir = false;
            }
            LocalDate fechaEmision = LocalDate.of(año, mes, dia);
            int posicion = Integer.parseInt(textPosicion.getText());
            if (posicion > 0 && posicion <= this.temporada.getNumeroCapitulos() + 1 && sePuedeAñadir) {
                if (posicion == this.temporada.getNumeroCapitulos() + 1) {
                    this.temporada.añadirCapitulo(fechaEmision, textNombre.getText());
                } else {
                    this.temporada.añadirCapitulo(posicion, fechaEmision, textNombre.getText());
                }
                this.haAñadido = true;
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se han introducido bien los datos", "ERROR", JOptionPane.ERROR_MESSAGE);
                setVisible(false);
            }
        }
        JOptionPane.showMessageDialog(rootPane, "No se han introducido bien los datos", "ERROR", JOptionPane.ERROR_MESSAGE);
        setVisible(false);

    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAñadirCapitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAñadirCapitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAñadirCapitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAñadirCapitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAñadirCapitulo dialog = new JDAñadirCapitulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel labelEmision;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPosicion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textFecha;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPosicion;
    // End of variables declaration//GEN-END:variables
}
