/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import modelo.ModeloListaCatalogo;
import modelo.ModeloListaPeliculas;
import vergeflix.Media;
import vergeflix.Pelicula;
import vergeflix.Vergeflix;

/**
 *
 * @author Heriberto Amezcua
 * @version 1.0
 * @since JDK 19
 */
public class JDGestorPeliculas extends javax.swing.JDialog {

    private int numPeliculas;
    private ArrayList<Pelicula> listaPeliculas;
    private ArrayList<Media> listaMedia;
    private ModeloListaPeliculas modelo;
    private Pelicula peliSeleccionada;

    /**
     * Creates new form JDGestorPeliculas
     */
    public JDGestorPeliculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDGestorPeliculas(java.awt.Frame parent, boolean modal, ArrayList<Media> listaMedia, int numPeliculas) {
        super(parent, modal);
        initComponents();
        //setting the initial values
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("play-icon.png");
        setIconImage(icon.getImage());
        setTitle("VERGEFLIX");
        JTableHeader header = tablePeliculas.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 14));
        tablePeliculas.setRowHeight(25);

        this.listaMedia = listaMedia;
        this.listaPeliculas = Vergeflix.peliculasCatalogo(listaMedia, numPeliculas);
        modelo = new ModeloListaPeliculas(this.listaPeliculas);
        tablePeliculas.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pItemEliminar = new javax.swing.JMenuItem();
        pItemModificar = new javax.swing.JMenuItem();
        pItemVotar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePeliculas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        mItemAñadir = new javax.swing.JMenuItem();

        pItemEliminar.setText("Eliminar");
        pItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pItemEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pItemEliminar);

        pItemModificar.setText("Modificar");
        pItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pItemModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pItemModificar);

        pItemVotar.setText("Votar");
        pItemVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pItemVotarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pItemVotar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablePeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablePeliculasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablePeliculas);

        menuOpciones.setText("OPCIONES");

        mItemAñadir.setText("Añadir Película");
        mItemAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAñadirActionPerformed(evt);
            }
        });
        menuOpciones.add(mItemAñadir);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePeliculasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePeliculasMousePressed
        //Sample 06: Show Popup menu at right click location
        if (evt.getButton() == MouseEvent.BUTTON3) {
            Point b = MouseInfo.getPointerInfo().getLocation();
            jPopupMenu1.setVisible(true);
            int row = tablePeliculas.rowAtPoint(evt.getPoint());
            int column = tablePeliculas.columnAtPoint(evt.getPoint());
            jPopupMenu1.show(this, (int) b.x - 50, (int) b.y - 50);
            tablePeliculas.setRowSelectionInterval(row, row);
            tablePeliculas.setColumnSelectionInterval(column, column);
            peliSeleccionada = this.listaPeliculas.get(row);
        }
    }//GEN-LAST:event_tablePeliculasMousePressed

    private void pItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pItemEliminarActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que quiere eliminar? " + this.peliSeleccionada.getNombre(), "Baja del sistema", JOptionPane.WARNING_MESSAGE);

        if (result == 0) {
            this.listaPeliculas.remove(this.peliSeleccionada);
            this.listaMedia.remove(this.peliSeleccionada);
            this.numPeliculas--;
        }
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_pItemEliminarActionPerformed

    private void pItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pItemModificarActionPerformed
        JDModificarPelicula modificar = new JDModificarPelicula(null, true, this.peliSeleccionada);
        modificar.setVisible(true);
        modelo.fireTableDataChanged();

    }//GEN-LAST:event_pItemModificarActionPerformed

    private void pItemVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pItemVotarActionPerformed
        try {
            int valorVoto = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Introduzca su voto del 1 al 10"));
            if (valorVoto >= 0 && valorVoto <= 10) {
                this.peliSeleccionada.votar(valorVoto);
                JOptionPane.showMessageDialog(rootPane, "Su voto ha sido introducido, gracias!");
                modelo.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Voto incorrecto, no se ha podido valorar", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Datos introduidos incorrectos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_pItemVotarActionPerformed

    private void mItemAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAñadirActionPerformed
        JDNuevaPelicula nuevaPelicula = new JDNuevaPelicula(null, true);
        nuevaPelicula.setVisible(true);

        if (nuevaPelicula.getHaAñadido()) {
            Pelicula nuevaPeli = nuevaPelicula.getNuevaPelicula();
            if (!Vergeflix.encuentraPelicula(listaPeliculas, nuevaPeli.getNombre())) {
                this.listaMedia.add(nuevaPeli);
                this.numPeliculas++;
                this.listaPeliculas.add(nuevaPeli);
                JOptionPane.showMessageDialog(rootPane, "Se ha añadido correctamente");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Ya hay una película con ese nombre dentro del catálogo", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            this.modelo.fireTableDataChanged();
        }

    }//GEN-LAST:event_mItemAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDGestorPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDGestorPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDGestorPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDGestorPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDGestorPeliculas dialog = new JDGestorPeliculas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mItemAñadir;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem pItemEliminar;
    private javax.swing.JMenuItem pItemModificar;
    private javax.swing.JMenuItem pItemVotar;
    private javax.swing.JTable tablePeliculas;
    // End of variables declaration//GEN-END:variables
}
