/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ModeloListaCapitulos;
import vergeflix.Capitulo;
import vergeflix.Temporada;

/**
 *
 * @author Heriberto Amezcua
 * @version 1.0
 * @since JDK 19
 */
public class JDGestorCapitulos extends javax.swing.JDialog {

    private ModeloListaCapitulos modelo;
    private Temporada temporada;
    private ArrayList<Capitulo> listaCapitulos;
    private Capitulo capituloSeleccionado;
    private int selectedRow;

    /**
     * Creates new form JDGestorCapitulos
     */
    public JDGestorCapitulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDGestorCapitulos(java.awt.Frame parent, boolean modal, Temporada temporada) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("play-icon.png");
        setIconImage(icon.getImage());
        setTitle("VERGEFLIX");
        this.temporada = temporada;
        this.listaCapitulos = temporada.getListaCapitulos();
        modelo = new ModeloListaCapitulos(this.listaCapitulos);
        tableCapitulos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pItemVotar = new javax.swing.JMenuItem();
        pItemEliminar = new javax.swing.JMenuItem();
        pItemModificar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCapitulos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItemAñadir = new javax.swing.JMenuItem();

        pItemVotar.setText("Votar");
        pItemVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pItemVotarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pItemVotar);

        pItemEliminar.setText("Eliminar");
        pItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pItemEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pItemEliminar);

        pItemModificar.setText("Modificar");
        pItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pItemModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pItemModificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableCapitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCapitulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableCapitulosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableCapitulos);

        jMenu1.setText("OPCIONES");

        mItemAñadir.setText("Añadir Capitulo");
        mItemAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAñadirActionPerformed(evt);
            }
        });
        jMenu1.add(mItemAñadir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableCapitulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCapitulosMousePressed
        //Sample 06: Show Popup menu at right click location
        if (evt.getButton() == MouseEvent.BUTTON3) {
            Point b = MouseInfo.getPointerInfo().getLocation();
            jPopupMenu1.setVisible(true);
            int row = tableCapitulos.rowAtPoint(evt.getPoint());
            int column = tableCapitulos.columnAtPoint(evt.getPoint());
            jPopupMenu1.show(this, (int) b.x - 400, (int) b.y - 250);
            tableCapitulos.setRowSelectionInterval(row, row);
            tableCapitulos.setColumnSelectionInterval(column, column);
            this.capituloSeleccionado = this.listaCapitulos.get(row);
            selectedRow = row;
        }
    }//GEN-LAST:event_tableCapitulosMousePressed

    private void mItemAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAñadirActionPerformed
        JDAñadirCapitulo capitulo = new JDAñadirCapitulo(null, true, this.temporada);
        capitulo.setVisible(true);

        if (capitulo.getHaAñadido()) {
            JOptionPane.showMessageDialog(rootPane, "El capítulo se ha añadido correctamente");
            capitulo.setVisible(false);
            modelo.fireTableDataChanged();
        } else {
            capitulo.setVisible(false);
        }
    }//GEN-LAST:event_mItemAñadirActionPerformed

    private void pItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pItemEliminarActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que quiere eliminar el capítulo " + this.capituloSeleccionado.getTitulo() + "?", "Eliminar", JOptionPane.WARNING_MESSAGE);

        if (result == 0) {
            this.temporada.eliminarCapitulo(this.capituloSeleccionado.getTitulo());
        }
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_pItemEliminarActionPerformed

    private void pItemVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pItemVotarActionPerformed
        int voto = JOptionPane.showConfirmDialog(rootPane, "¿Le gusta el capítulo?");

        if (voto == 0) {
            this.temporada.meGusta(this.selectedRow + 1, true);
            JOptionPane.showMessageDialog(rootPane, "¡Gracias por valorar el capítulo!");
        }
        if (voto == 1) {
            this.temporada.meGusta(this.selectedRow + 1, false);
            JOptionPane.showMessageDialog(rootPane, "¡Gracias por valorar el capítulo!");
        }
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_pItemVotarActionPerformed

    private void pItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pItemModificarActionPerformed
        JDModificarCapitulo modificar = new JDModificarCapitulo(null, true, this.temporada, this.capituloSeleccionado);
        modificar.setVisible(true);

        if (modificar.getHaModificado()) {
            JOptionPane.showMessageDialog(rootPane, "Se ha modificado el capítulo");
            modificar.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se ha podido modificar el capítulo", "ERROR", JOptionPane.ERROR_MESSAGE);
            modificar.setVisible(false);
        }
        modelo.fireTableDataChanged();

    }//GEN-LAST:event_pItemModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDGestorCapitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDGestorCapitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDGestorCapitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDGestorCapitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDGestorCapitulos dialog = new JDGestorCapitulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mItemAñadir;
    private javax.swing.JMenuItem pItemEliminar;
    private javax.swing.JMenuItem pItemModificar;
    private javax.swing.JMenuItem pItemVotar;
    private javax.swing.JTable tableCapitulos;
    // End of variables declaration//GEN-END:variables
}
