/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import funciones.ValidarDatos;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import vergeflix.Serie;

/**
 *
 * @author Heriberto Amezcua
 * @version 1.0
 * @since JDK 19
 */
public class JDModificarSerie extends javax.swing.JDialog {

    private Serie serie;

    /**
     * Creates new form JDModificarSerie
     */
    public JDModificarSerie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDModificarSerie(java.awt.Frame parent, boolean modal, Serie serie) {
        super(parent, modal);
        initComponents();

        ImageIcon icon = new ImageIcon("play-icon.png");
        setIconImage(icon.getImage());
        setTitle("VERGEFLIX");
        setResizable(false);
        setLocationRelativeTo(null);

        this.serie = serie;
        labelTitulo.setText("Modificando " + serie.getNombre());
        textTitulo.setText(serie.getNombre());
        textEdad.setText("" + serie.getCalificacionEdad());

        StringBuilder fechaEstr = new StringBuilder(serie.getFechaEstreno().toString());
        int año = Integer.parseInt(fechaEstr.toString().split("-")[0]);
        int mes = Integer.parseInt(fechaEstr.toString().split("-")[1]);
        int dia = Integer.parseInt(fechaEstr.toString().split("-")[2]);
        textFechaEstr.setText(dia + "-" + mes + "-" + año);
        if (serie.getEstaDisponible()) {
            checkSi.doClick();
        } else {
            checkNo.doClick();
        }
        StringBuilder fechaInc = new StringBuilder(serie.getFechaIncorporacionAlCatalogo().toString());
        int año2 = Integer.parseInt(fechaInc.toString().split("-")[0]);
        int mes2 = Integer.parseInt(fechaInc.toString().split("-")[1]);
        int dia2 = Integer.parseInt(fechaInc.toString().split("-")[2]);
        textIncorporacion.setText(dia2 + "-" + mes2 + "-" + año2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        textTitulo = new javax.swing.JTextField();
        labelNuevoTitulo = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        textFechaEstr = new javax.swing.JTextField();
        labelIncorporacion = new javax.swing.JLabel();
        textIncorporacion = new javax.swing.JTextField();
        labelFechaEstreno = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        textEdad = new javax.swing.JTextField();
        checkSi = new javax.swing.JCheckBox();
        checkNo = new javax.swing.JCheckBox();
        labelDisponibilidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelTitulo.setText("Modificando...");

        textTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelNuevoTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNuevoTitulo.setText("Título:");

        labelEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEdad.setText("Calificación de Edad:");

        textFechaEstr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelIncorporacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelIncorporacion.setText("Fecha de Incorporación:");

        textIncorporacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelFechaEstreno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFechaEstreno.setText("Fecha de Estreno");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        textEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        checkSi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkSi.setText("Si");

        checkNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkNo.setText("No");

        labelDisponibilidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDisponibilidad.setText("Disponible:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFechaEstreno)
                            .addComponent(labelEdad)
                            .addComponent(labelNuevoTitulo)
                            .addComponent(labelIncorporacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFechaEstr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDisponibilidad)
                                .addGap(137, 137, 137)
                                .addComponent(checkSi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkNo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelTitulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoTitulo))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEdad))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIncorporacion))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDisponibilidad)
                    .addComponent(checkSi)
                    .addComponent(checkNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFechaEstr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaEstreno))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ArrayList<JTextField> listaCampos = new ArrayList<>();

        textTitulo.setName("Titulo");
        textEdad.setName("Edad");
        textIncorporacion.setName("Incorporacion");
        textFechaEstr.setName("FechaEstr");

        listaCampos.add(textTitulo);
        listaCampos.add(textEdad);
        listaCampos.add(textIncorporacion);
        listaCampos.add(textFechaEstr);

        boolean sePuedeModificar = true;
        for (JTextField text : listaCampos) {
            if (!text.getText().isBlank()) {
                switch (text.getName()) {
                    case "Titulo" -> {
                        if (ValidarDatos.validarTitulo(text.getText())) {
                            this.serie.setNombre(text.getText());

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "El título introducido es erróneo", "ERROR", JOptionPane.ERROR_MESSAGE);
                            setVisible(false);

                        }
                    }
                    case "Edad" -> {
                        if (ValidarDatos.validarCalificacionEdad(Integer.parseInt(text.getText()))) {
                            this.serie.setCalificacionEdad(Integer.parseInt(text.getText()));
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "La calificación de edad introducida es errónea", "ERROR", JOptionPane.ERROR_MESSAGE);
                            setVisible(false);

                        }
                    }
                    case "Incorporacion" -> {
                        if (ValidarDatos.validarFecha(text.getText())) {
                            StringBuilder fechaIntr = new StringBuilder(text.getText());
                            int dia = Integer.parseInt(fechaIntr.toString().split("-")[0]);
                            int mes = Integer.parseInt(fechaIntr.toString().split("-")[1]);
                            int año = Integer.parseInt(fechaIntr.toString().split("-")[2]);

                            this.serie.setFechaIncorporacionAlCatalogo(LocalDate.of(año, mes, dia));
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "La fecha de incorporación introducida es errónea", "ERROR", JOptionPane.ERROR_MESSAGE);
                            setVisible(false);

                        }
                    }
                    case "FechaEstr" -> {
                        if (ValidarDatos.validarFecha(text.getText())) {
                            StringBuilder fechaEstr = new StringBuilder(text.getText());
                            int dia = Integer.parseInt(fechaEstr.toString().split("-")[0]);
                            int mes = Integer.parseInt(fechaEstr.toString().split("-")[1]);
                            int año = Integer.parseInt(fechaEstr.toString().split("-")[2]);

                            this.serie.setFechaEstreno(LocalDate.of(año, mes, dia));
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "La fecha de incorporación introducida es errónea", "ERROR", JOptionPane.ERROR_MESSAGE);
                            setVisible(false);

                        }

                    }
                }
            }
        }

        if (checkSi.isSelected()) {
            this.serie.setEstaDisponible(true);
        } else {
            this.serie.setEstaDisponible(false);

        }
        JOptionPane.showMessageDialog(rootPane, "La Serie se ha modificado correctamente!!");
        setVisible(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDModificarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDModificarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDModificarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDModificarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDModificarSerie dialog = new JDModificarSerie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox checkNo;
    private javax.swing.JCheckBox checkSi;
    private javax.swing.JLabel labelDisponibilidad;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelFechaEstreno;
    private javax.swing.JLabel labelIncorporacion;
    private javax.swing.JLabel labelNuevoTitulo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textEdad;
    private javax.swing.JTextField textFechaEstr;
    private javax.swing.JTextField textIncorporacion;
    private javax.swing.JTextField textTitulo;
    // End of variables declaration//GEN-END:variables
}
