/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import funciones.ValidarDatos;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import vergeflix.Serie;

/**
 *
 * @author Heriberto Amezcua
 * @version 1.0
 * @since JDK 19
 */
public class JDNuevaSerie extends javax.swing.JDialog {

    private Serie nuevaSerie;
    private boolean haAñadido;

    /**
     * Creates new form JDNuevaSerie
     */
    public JDNuevaSerie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //setting the initial values
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("play-icon.png");
        setIconImage(icon.getImage());
        setTitle("VERGEFLIX");
        this.haAñadido = false;
    }

    public Serie getNuevaSerie() {
        return this.nuevaSerie;
    }

    public boolean getHaAñadido() {
        return this.haAñadido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDisponible = new javax.swing.ButtonGroup();
        textEdad = new javax.swing.JTextField();
        labelEdad = new javax.swing.JLabel();
        textFechaInc = new javax.swing.JTextField();
        labelFechaInc = new javax.swing.JLabel();
        textFechaEstr = new javax.swing.JTextField();
        labelDisponible = new javax.swing.JLabel();
        labelFechaEstr = new javax.swing.JLabel();
        checkDisponibleSi = new javax.swing.JCheckBox();
        checkDisponibleNo = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        textTitulo = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEdad.setText("Calificación de edad:");

        labelFechaInc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFechaInc.setText("Fecha de Incorporación:");

        textFechaEstr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaEstrActionPerformed(evt);
            }
        });

        labelDisponible.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDisponible.setText("¿Está Disponible?");

        labelFechaEstr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFechaEstr.setText("Fecha de Estreno:");

        btnGroupDisponible.add(checkDisponibleSi);
        checkDisponibleSi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkDisponibleSi.setText("Si");

        btnGroupDisponible.add(checkDisponibleNo);
        checkDisponibleNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkDisponibleNo.setText("No");
        checkDisponibleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDisponibleNoActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAñadir.setText("AÑADIR");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Formulario Nueva Serie");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre.setText("Título:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDisponible)
                                .addGap(51, 51, 51)
                                .addComponent(checkDisponibleSi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkDisponibleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFechaEstr)
                                .addGap(18, 18, 18)
                                .addComponent(textFechaEstr))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEdad)
                                .addGap(18, 18, 18)
                                .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFechaInc)
                                .addGap(18, 18, 18)
                                .addComponent(textFechaInc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTitulo)
                                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdad)
                    .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaInc)
                    .addComponent(textFechaInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkDisponibleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDisponible)
                        .addComponent(checkDisponibleSi)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaEstr)
                    .addComponent(textFechaEstr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        boolean sePuedeAñadir = true;
        if (!ValidarDatos.validarTitulo(textTitulo.getText())) {
            sePuedeAñadir = false;
        }
        if (!textEdad.getText().isBlank()) {
            if (!ValidarDatos.validarCalificacionEdad(Integer.parseInt(textEdad.getText()))) {
                sePuedeAñadir = false;
            }
        }
        if (!ValidarDatos.validarFecha(textFechaInc.getText())) {
            sePuedeAñadir = false;
        }
        if (!ValidarDatos.validarFecha(textFechaEstr.getText())) {
            sePuedeAñadir = false;
        }
        if (sePuedeAñadir) {
            boolean estaDisponible = false;
            if (btnGroupDisponible.getSelection().equals(checkDisponibleSi)) {
                estaDisponible = true;
            }

            StringBuilder fechaInc = new StringBuilder(textFechaInc.getText());
            int dia = Integer.parseInt(fechaInc.toString().split("-")[0]);
            int mes = Integer.parseInt(fechaInc.toString().split("-")[1]);
            int año = Integer.parseInt(fechaInc.toString().split("-")[2]);

            StringBuilder fechaEstr = new StringBuilder(textFechaEstr.getText());
            int dia2 = Integer.parseInt(fechaEstr.toString().split("-")[0]);
            int mes2 = Integer.parseInt(fechaEstr.toString().split("-")[1]);
            int año2 = Integer.parseInt(fechaEstr.toString().split("-")[2]);

            Serie nuevaSerie = new Serie(textTitulo.getText(), Integer.parseInt(textEdad.getText()), LocalDate.of(año, mes, dia), estaDisponible, LocalDate.of(año2, mes2, dia2));
            this.nuevaSerie = nuevaSerie;
            this.haAñadido = true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al introducir los datos, no se ha podido añadir", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        setVisible(false);
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void textFechaEstrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaEstrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaEstrActionPerformed

    private void checkDisponibleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDisponibleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDisponibleNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDNuevaSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDNuevaSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDNuevaSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDNuevaSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDNuevaSerie dialog = new JDNuevaSerie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGroupDisponible;
    private javax.swing.JCheckBox checkDisponibleNo;
    private javax.swing.JCheckBox checkDisponibleSi;
    private javax.swing.JLabel labelDisponible;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelFechaEstr;
    private javax.swing.JLabel labelFechaInc;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textEdad;
    private javax.swing.JTextField textFechaEstr;
    private javax.swing.JTextField textFechaInc;
    private javax.swing.JTextField textTitulo;
    // End of variables declaration//GEN-END:variables
}
