/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import funciones.ValidarDatos;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import vergeflix.Pelicula;
import vergeflix.Tematica;

/**
 *
 * @author Heriberto Amezcua
 * @version 1.0
 * @since JDK 19
 */
public class JDNuevaPelicula extends javax.swing.JDialog {

    private Pelicula nuevaPelicula;
    private boolean haAñadido;

    /**
     * Creates new form JDNuevaPelicula
     */
    public JDNuevaPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //setting the initial values
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("play-icon.png");
        setIconImage(icon.getImage());
        setTitle("VERGEFLIX");
        this.haAñadido = false;
    }

    public Pelicula getNuevaPelicula() {
        return this.nuevaPelicula;
    }

    public boolean getHaAñadido() {
        return this.haAñadido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDisponible = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelFechaInc = new javax.swing.JLabel();
        labelDisponible = new javax.swing.JLabel();
        labelDirector = new javax.swing.JLabel();
        labelActor = new javax.swing.JLabel();
        labelDuracion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        textTitulo = new javax.swing.JTextField();
        textEdad = new javax.swing.JTextField();
        textFechaInc = new javax.swing.JTextField();
        textDirector = new javax.swing.JTextField();
        textActor = new javax.swing.JTextField();
        textDuracion = new javax.swing.JTextField();
        checkDisponibleSi = new javax.swing.JCheckBox();
        checkDisponibleNo = new javax.swing.JCheckBox();
        comboTematicas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Formulario Nueva Película");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre.setText("Título:");

        labelEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEdad.setText("Calificación de edad:");

        labelFechaInc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFechaInc.setText("Fecha de Incorporación:");

        labelDisponible.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDisponible.setText("¿Está Disponible?");

        labelDirector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDirector.setText("Director:");

        labelActor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelActor.setText("Actor:");

        labelDuracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDuracion.setText("Duracion:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione temática:");

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAñadir.setText("AÑADIR");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnGroupDisponible.add(checkDisponibleSi);
        checkDisponibleSi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkDisponibleSi.setText("Si");

        btnGroupDisponible.add(checkDisponibleNo);
        checkDisponibleNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkDisponibleNo.setText("No");

        comboTematicas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboTematicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciencia Ficción", "Fantasía", "Suspense", "Drama", "Terror", "Comedia" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDisponible)
                                .addGap(51, 51, 51)
                                .addComponent(checkDisponibleSi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkDisponibleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDirector)
                                .addGap(18, 18, 18)
                                .addComponent(textDirector))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelActor)
                                .addGap(18, 18, 18)
                                .addComponent(textActor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEdad)
                                .addGap(18, 18, 18)
                                .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFechaInc)
                                .addGap(18, 18, 18)
                                .addComponent(textFechaInc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDuracion)
                                .addGap(18, 18, 18)
                                .addComponent(textDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboTematicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTitulo)
                                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdad)
                    .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaInc)
                    .addComponent(textFechaInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkDisponibleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDisponible)
                        .addComponent(checkDisponibleSi)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDirector)
                    .addComponent(textDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelActor)
                    .addComponent(textActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracion)
                    .addComponent(textDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboTematicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        boolean sePuedeAñadir = true;
        if (!ValidarDatos.validarTitulo(textTitulo.getText())) {
            sePuedeAñadir = false;
        }
        if(!textEdad.getText().isBlank()){          
            if (!ValidarDatos.validarCalificacionEdad(Integer.parseInt(textEdad.getText()))) {
                sePuedeAñadir = false;
            }
        }
        if (!ValidarDatos.validarFecha(textFechaInc.getText())) {
            sePuedeAñadir = false;
        }
        if (!ValidarDatos.validarNombrePersona(textDirector.getText())) {
            sePuedeAñadir = false;
        }
        if (!ValidarDatos.validarNombrePersona(textActor.getText())) {
            sePuedeAñadir = false;
        }
        if(!textDuracion.getText().isBlank()){
            if (!ValidarDatos.validarDuracion(Integer.parseInt(textDuracion.getText()))) {
                sePuedeAñadir = false;

            }          
        }
        if (sePuedeAñadir) {
            boolean estaDisponible = false;
            if (btnGroupDisponible.getSelection().equals(checkDisponibleSi)) {
                estaDisponible = true;
            }

            Tematica tematica = Tematica.CIENCIA_FICCION;
            switch (comboTematicas.getSelectedIndex()) {
                case 0 -> {
                    tematica = Tematica.CIENCIA_FICCION;
                }
                case 1 -> {
                    tematica = Tematica.FANTASIA;

                }
                case 2 -> {
                    tematica = Tematica.SUSPENSE;

                }
                case 3 -> {
                    tematica = Tematica.DRAMA;

                }
                case 4 -> {
                    tematica = Tematica.TERROR;

                }
                case 5 -> {
                    tematica = Tematica.COMEDIA;
                }
            }

            StringBuilder fechaInc = new StringBuilder(textFechaInc.getText());
            int dia = Integer.parseInt(fechaInc.toString().split("-")[0]);
            int mes = Integer.parseInt(fechaInc.toString().split("-")[1]);
            int año = Integer.parseInt(fechaInc.toString().split("-")[2]);

            Pelicula nuevaPelicula = new Pelicula(textTitulo.getText(), Integer.parseInt(textEdad.getText()), LocalDate.of(año, mes, dia), estaDisponible, textDirector.getText(), textActor.getText(), Integer.parseInt(textDuracion.getText()), tematica);
            this.nuevaPelicula = nuevaPelicula;
            this.haAñadido = true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al introducir los datos, no se ha podido añadir", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        setVisible(false);

    }//GEN-LAST:event_btnAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDNuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDNuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDNuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDNuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDNuevaPelicula dialog = new JDNuevaPelicula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGroupDisponible;
    private javax.swing.JCheckBox checkDisponibleNo;
    private javax.swing.JCheckBox checkDisponibleSi;
    private javax.swing.JComboBox<String> comboTematicas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelActor;
    private javax.swing.JLabel labelDirector;
    private javax.swing.JLabel labelDisponible;
    private javax.swing.JLabel labelDuracion;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelFechaInc;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textActor;
    private javax.swing.JTextField textDirector;
    private javax.swing.JTextField textDuracion;
    private javax.swing.JTextField textEdad;
    private javax.swing.JTextField textFechaInc;
    private javax.swing.JTextField textTitulo;
    // End of variables declaration//GEN-END:variables
}
